tests:
  vaults:
    # Tests vault creation and deletion operations
    enabled: true
    count: 1000
    prefix: vault-test
    clean_up: false # ONLY set to true if previous test run ended prematurely and wasn't able to clean up data. See README.MD for more details.
  e2e:
    # Tests full lifecycle (create vault -> load attributes -> delete attributes -> delete vault)
    enabled: true
    count: 1000
    prefix: e2e-test
    clean_up: false # ONLY set to true if previous test run ended prematurely and wasn't able to clean up data. See README.MD for more details.
  attributes:
    # Tests standalone attribute operations
    enabled: true
    count: 1000
    vault_count: 100  # Number of vaults to create for attribute operations
    prefix: attr-test
    clean_up: false # ONLY set to true if previous test run ended prematurely and wasn't able to clean up data. See README.MD for more details.
  tokenizer:
    # Tests tokenize only
    enabled: true
    count: 100
    vault_count: 1 # Number of vaults to create for tokenize operations
    prefix: tokenizer-test
    realm: data-loader # IMPORTANT: This needs to match the realm you are running your tests
    clean_up: false
    value_min: 4 # The minimum size of values to generate
    value_max: 32 # The maximum size of values to generate
    tokens_per_job: 3 # The number of tokens per operation to generate
    token_type: EPHEMERAL # Can be EPHEMERAL or PERSISTENT
  tokenizer_translate_e2e:
    # Tests tokenize + translate e2e time
    enabled: true
    count: 100
    vault_count: 1 # Number of vaults to create for tokenize/translate operations
    prefix: tokenizer-e2e-test
    realm: data-loader # IMPORTANT: This needs to match the realm you are running your tests
    clean_up: false
    value_min: 4 # The minimum size of values to generate
    value_max: 32 # The maximum size of values to generate
    tokens_per_job: 1 # The number of tokens per operation to generate
    token_type: EPHEMERAL # Can be EPHEMERAL or PERSISTENT
concurrency:
  # note: count values for all sections (especially vault_count for attributes)
  # should be greater than concurrency values for accurate performance measurements
  # e.g: To fire 64 concurrent attribute operation requests, there needs to be 64
  # or more vaults (vault_count>64)
  - 16
  - 32
  - 64
log_level: debug  # Available levels: trace, debug, info, error

#reports:               # optional define custom path for test reports. Default is ./reports/manetu-perf-results-<hh-mm-MM-dd-yyyy>.[csv|json]
#  csv: "reports.csv"   # Path for CSV report output
#  json: "reports.json" # Path for JSON report output